export const NETRAX_COLORS = {
  background: '#0B0F14',
  secondaryBackground: '#0F151C',
  card: '#111820',
  elevatedCard: '#151D26',
  border: '#26313D',
  primaryText: '#F8FAFC',
  secondaryText: '#94A3B8',
  mutedText: '#64748B',
  accent: '#2DD4FF',
  success: '#22C55E',
  warning: '#F59E0B',
  danger: '#EF4444',
} as const;

export const COLOR_SWATCHES = [
  { name: 'Background', hex: '#0B0F14', role: 'Main surface background canvas', contrast: 'Dark Base' },
  { name: 'Secondary Background', hex: '#0F151C', role: 'Sidebar & tool bars', contrast: 'Dark Layer 2' },
  { name: 'Card', hex: '#111820', role: 'Container & component cards', contrast: 'Dark Layer 3' },
  { name: 'Elevated Card', hex: '#151D26', role: 'Modals, popovers & hovering cards', contrast: 'Dark Layer 4' },
  { name: 'Border', hex: '#26313D', role: 'Divider lines, card outlines & inputs', contrast: '1px separator' },
  { name: 'Primary Text', hex: '#F8FAFC', role: 'Headings, primary values & critical labels', contrast: 'High (18.2:1)' },
  { name: 'Secondary Text', hex: '#94A3B8', role: 'Body copy, descriptions & secondary labels', contrast: 'Medium (9.4:1)' },
  { name: 'Muted Text', hex: '#64748B', role: 'Metadata, timestamps & placeholders', contrast: 'Subtle (5.6:1)' },
  { name: 'Accent (Cyan)', hex: '#2DD4FF', role: 'AI features, active states, detections & primary actions', contrast: 'Vibrant focus' },
  { name: 'Success', hex: '#22C55E', role: 'Active status, online cameras, high confidence', contrast: 'Operational OK' },
  { name: 'Warning', hex: '#F59E0B', role: 'Medium confidence, degraded state, pending notice', contrast: 'Alert Advisory' },
  { name: 'Danger', hex: '#EF4444', role: 'High priority alerts, offline feeds, incidents', contrast: 'Critical Action' },
];

export const TYPOGRAPHY_STYLES = [
  {
    name: 'Display 32 / Bold',
    size: '32px',
    lineHeight: '40px',
    weight: '700 (Bold)',
    tracking: '-0.02em',
    usage: 'Intelligence view hero titles & screen anchors',
    className: 'text-[32px] leading-[40px] font-bold tracking-tight',
    sample: 'SURVEILLANCE INTELLIGENCE PLATFORM',
  },
  {
    name: 'KPI Number 28 / Bold',
    size: '28px',
    lineHeight: '34px',
    weight: '700 (Bold)',
    tracking: '-0.01em',
    usage: 'Key metrics, counts & analytical stats',
    className: 'text-[28px] leading-[34px] font-bold tracking-tight font-mono',
    sample: '1,429 DETECTIONS',
  },
  {
    name: 'Heading 24 / Semibold',
    size: '24px',
    lineHeight: '32px',
    weight: '600 (Semibold)',
    tracking: '-0.015em',
    usage: 'Section headers & modal titles',
    className: 'text-[24px] leading-[32px] font-semibold tracking-tight',
    sample: 'Cross-Camera Correlation Matrix',
  },
  {
    name: 'Section 18 / Semibold',
    size: '18px',
    lineHeight: '26px',
    weight: '600 (Semibold)',
    tracking: '-0.01em',
    usage: 'Component group headers & card sections',
    className: 'text-[18px] leading-[26px] font-semibold',
    sample: 'Live Feed Feeds — Sector 12 Hub',
  },
  {
    name: 'Card Title 16 / Semibold',
    size: '16px',
    lineHeight: '24px',
    weight: '600 (Semibold)',
    tracking: 'normal',
    usage: 'Card titles, table headers & modal titles',
    className: 'text-[16px] leading-[24px] font-semibold',
    sample: 'Case #NX-1024 • Stolen Vehicle Alert',
  },
  {
    name: 'Body 14 / Regular',
    size: '14px',
    lineHeight: '22px',
    weight: '400 (Regular)',
    tracking: 'normal',
    usage: 'Primary body text, descriptions & form inputs',
    className: 'text-[14px] leading-[22px] font-normal text-[#94A3B8]',
    sample: 'Vehicle matched silver sedan fleeing eastbound toward highway exit 4B.',
  },
  {
    name: 'Small 12 / Regular',
    size: '12px',
    lineHeight: '18px',
    weight: '400 (Regular)',
    tracking: 'normal',
    usage: 'Secondary metadata, tags & table sub-rows',
    className: 'text-[12px] leading-[18px] font-normal text-[#94A3B8]',
    sample: 'Last sync: 14 Sept 2026 • 20:43:17 UTC',
  },
  {
    name: 'Caption 11 / Medium',
    size: '11px',
    lineHeight: '16px',
    weight: '500 (Medium)',
    tracking: '0.04em',
    usage: 'Status badges, tracking IDs & technical telemetry tags',
    className: 'text-[11px] leading-[16px] font-medium uppercase tracking-wider',
    sample: 'CAMERA C-17 • AI VERIFIED',
  },
];

export const SPACING_SYSTEM = [
  { token: 'space-1', value: '4px', usage: 'Micro gaps, inner badge padding, dot spacing' },
  { token: 'space-2', value: '8px', usage: 'Base grid unit, icon padding, button gap' },
  { token: 'space-3', value: '12px', usage: 'Tight container padding, input padding' },
  { token: 'space-4', value: '16px', usage: 'Card inner padding, standard element gap' },
  { token: 'space-6', value: '24px', usage: 'Medium container padding, section separation' },
  { token: 'space-8', value: '32px', usage: 'Large container separation, panel gutters' },
  { token: 'space-10', value: '40px', usage: 'Major view division gutters' },
  { token: 'space-12', value: '48px', usage: 'Primary screen boundaries and layout paddings' },
];

export const RADIUS_SYSTEM = [
  { token: 'radius-sm', value: '6px', usage: 'Buttons, badges, inputs, map chips' },
  { token: 'radius-md', value: '8px', usage: 'Cards, player panels, dropdown menus' },
  { token: 'radius-lg', value: '12px', usage: 'Elevated modals, upload zones, primary panels' },
];
